install.packages("party")
setwd("D:/data mining/data read")
getwd()
list.files()
D<-read.csv("data.csv",header = TRUE)
head(D)
View(D)
D[D$age=="youth",]
youth<-D[D$senior=="youth",]
youth
nrow(youth)
table(youth$Class)
p1<-(D[D$Class=="yes",])
p1/nrow(D)
p2<-(D[D$Class=="no",])
p2
p2/nrow(D)
plot(D$income,D$age)
plot(D$income,D$student)
plot(D$income,D$credit_rating)
plot(D$income,D$Class)
plot(D$age,D$income)
plot(D$age,D$student)
plot(D$age,D$credit_rating)
plot(D$age,D$Class)
plot(D)
D[D$income=="high",]
high<-D[D$income=="high",]
high
nrow(high)
table(high$Class)
p1<-(D[D$Class=="yes",])
p1/nrow(D)
p2<-(D[D$Class=="no",])
p2
p2/nrow(D)
D[D$income=="low",]
low<-D[D$income=="low",]
low
nrow(low)
table(low$Class)
p1<-(D[D$Class=="yes",])
p1/nrow(D)
p2<-(D[D$Class=="no",])
p2
p2/nrow(D)
D[D$income=="medium",]
high<-D[D$income=="medium",]
high
nrow(medium)
table(medium$Class)
p1<-(D[D$Class=="yes",])
p1/nrow(D)
p2<-(D[D$Class=="no",])
p2
p2/nrow(D)
D[D$student=="yes",]
yes<-D[D$student=="yes",]
yes
nrow(yes)
table(yes$Class)
p1<-(D[D$Class=="yes",])
p1/nrow(D)
p2<-(D[D$Class=="no",])
p2
p2/nrow(D)
D[D$student=="no",]
nostudent<-D[D$student=="no",]
nostudent
nrow(no)
table(no$Class)
p1<-(D[D$Class=="yes",])
p1/nrow(D)
p2<-(D[D$Class=="no",])
p2
p2/nrow(D)
print(head(class))
input.dat <- class[c(1:105),]
png(file = "decision_tree.png")
output.tree <- ctree(
  RID ~ age + income + student +credit_rating +class, 
  data = input.dat)
plot(D$income,D$age)
plot(D$income,D$student)
plot(D$income,D$credit_rating)
plot(D$income,D$Class)
plot(D$age,D$income)
plot(D$age,D$student)
plot(D$age,D$credit_rating)
plot(D$age,D$Class)
plot(D)
